export const KINSHASA_COMMUNES = [
  "Bandalungwa",
  "Barumbu",
  "Bumbu",
  "Gombe",
  "Kalamu",
  "Kasa-Vubu",
  "Kimbanseke",
  "Kinshasa",
  "Kintambo",
  "Kisenso",
  "Lemba",
  "Limete",
  "Lingwala",
  "Makala",
  "Maluku",
  "Masina",
  "Matete",
  "Mont-Ngafula",
  "Ndjili",
  "Ngaba",
  "Ngaliema",
  "Ngiri-Ngiri",
  "Nsele",
  "Selembao",
] as const;

export const MARITAL_STATUS_OPTIONS = [
  "Célibataire",
  "Marié(e)",
  "Veuf / Veuve",
  "Divorcé(e)",
  "Séparé(e)",
  "Union libre",
  "Non renseigné",
] as const;

export const COUNTRIES = [
  "RDC",
  "Afrique du Sud",
  "Algérie",
  "Allemagne",
  "Angola",
  "Arabie saoudite",
  "Argentine",
  "Australie",
  "Autriche",
  "Belgique",
  "Bénin",
  "Botswana",
  "Brésil",
  "Burkina Faso",
  "Burundi",
  "Cameroun",
  "Canada",
  "Chine",
  "Congo",
  "Côte d’Ivoire",
  "Égypte",
  "Espagne",
  "États-Unis",
  "Éthiopie",
  "France",
  "Gabon",
  "Ghana",
  "Guinée",
  "Inde",
  "Italie",
  "Japon",
  "Kenya",
  "Maroc",
  "Nigeria",
  "Ouganda",
  "Pays-Bas",
  "Portugal",
  "Royaume-Uni",
  "Rwanda",
  "Sénégal",
  "Suisse",
  "Tanzanie",
  "Tchad",
  "Togo",
  "Tunisie",
  "Turquie",
  "Zambie",
  "Zimbabwe",
] as const;

export function isKinshasaCity(city: string): boolean {
  return city.trim().toLocaleLowerCase("fr-FR") === "kinshasa";
}